### ISSUE TITLE
When spanning is 'none', fallback should be used in CSS env variables

### ISSUE THREAD

**Issue by kenchris** [foldable-devices/spanning-css-polyfill#26]
meaning 

```css

@media (spanning: none) {
  .map {
    flex: 1 1 env(fold-left, 200px);
  }
}
```

should result in `flex: 1 1 200px`

**Comment by darktears** [comment]
but why? can't you just do : 
```css
@media (spanning: none) {
  .map {
    flex: 1 1 100vw;
  }
```

In a non spanning mode it's no different than if you are on a regular window. I haven't test on the emulator but most likely fold-left doesn't even have a value.
